**DeeQu**, an open source data quality library, addresses data quality monitoring req**uirement**s and
can scale to large datasets. DeeQu is built on top of Apache Spark to define "**unit test for data**"

With DeeQu, you can populate data quality metrics and define data quality rules easily

[**Current supported functionalities**](https://github.com/awslabs/python-deequ/blob/master/docs/checks.md)

[**Documentation**](https://pydeequ.readthedocs.io/_/downloads/en/latest/pdf/)

In [1]:
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz
!tar xf spark-3.1.1-bin-hadoop2.7.tgz
!pip install -q findspark

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre-headless_11.0.29%2b7-1ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jdk-headless_11.0.29%2b7-1ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

In [60]:
!pwd

/content

In [61]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop2.7"

In [62]:
import findspark
findspark.init()

In [5]:
!pip install pydeequ

Collecting pydeequ
  Downloading pydeequ-1.5.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from pydeequ) (2.0.2)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from pydeequ) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23.0->pydeequ) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23.0->pydeequ) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23.0->pydeequ) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23.0->pydeequ) (1.17.0)
Downloading pydeequ-1.5.0-py3-none-any.whl (37 kB)
Installing collected packages: pydeequ
Successfully installed pydeequ-1.5.0

In [6]:
!pip install pyspark==3.1.1

Collecting pyspark==3.1.1
  Downloading pyspark-3.1.1.tar.gz (212.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.3/212.3 MB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9 (from pyspark==3.1.1)
  Downloading py4j-0.10.9-py2.py3-none-any.whl.metadata (1.3 kB)
Downloading py4j-0.10.9-py2.py3-none-any.whl (198 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 kB 16.7 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.1.1-py2.py3-none-any.whl size=212767583 sha256=7d0195a73ecf2af0e7f7cef6a0b8d9f931d2227dad68c0fe85815250ebe56dc0
  Stored in directory: /root/.cache/pip/wheels/27/e9/18/962270b7ab2321b060deb462c01084a27593f8a157e4140c86
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.9
    Uninstalling py4j-0.10.9.9:
      Successfully uninstalled py4j-0.10.9.9
  Attempting uninstall: pyspark
    Found existing installation: pyspark 4.0.2
    Uninstalling pyspark-4.0.2:
      Successfully uninstalled pyspark-4.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 1.0.2 requires pyspark[connect]~=4.0.0, but you have pyspark 3.1.1 which is incompatible.
Successfully installed py4j-0.10.9 pyspark-3.1.1

In [7]:
import os
os.environ['SPARK_VERSION'] = '3.1.1'

In [9]:
pip install findspark

Requirement already satisfied: findspark in /usr/local/lib/python3.12/dist-packages (2.0.1)

In [11]:
!apt-get update
!apt-get install openjdk-11-jdk -y

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:11 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [87.4 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,934 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,870 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,786 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,303 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,830 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,615 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:20 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,002 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,164 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [84.0 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Fetched 38.4 MB in 7s (5,861 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless
  session-migration x11-utils
Suggested packages:
  libxt-doc openjdk-11-demo openjdk-11-source visualvm libnss-mdns
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre
  openjdk-11-jre-headless session-migration x11-utils
0 upgraded, 20 newly installed, 0 to remove and 142 not upgraded.
Need to get 124 MB of archives.
After this operation, 277 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre-headless amd64 11.0.30+7-1ubuntu1~22.04 [42.6 MB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre amd64 11.0.30+7-1ubuntu1~22.04 [214 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.30+7-1ubuntu1~22.04 [73.7 MB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk amd64 11.0.30+7-1ubuntu1~22.04 [2,926 kB]
Fetched 124 MB in 2s (49.7 MB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../05-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../06-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../11-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../12-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../13-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../14-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../15-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../16-openjdk-11-jre-headless_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../17-openjdk-11-jre_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jdk-headless:amd64.
Preparing to unpack .../18-openjdk-11-jdk-headless_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../19-openjdk-11-jdk_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up openjdk-11-jre:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Setting up openjdk-11-jdk-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up openjdk-11-jdk:amd64 (11.0.30+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.7) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [13]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

In [63]:
!java -version

openjdk version "11.0.30" 2026-01-20
OpenJDK Runtime Environment (build 11.0.30+7-post-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.30+7-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)

In [64]:
from pyspark.sql import SparkSession, Row
import pydeequ
import pandas as pd

spark = (SparkSession
             .builder
             .config("spark.jars.packages", pydeequ.deequ_maven_coord)
             .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
             .getOrCreate())

In [17]:
!git clone https://github.com/Titou310014/Projet-tutore-DATA-QUALITY

Cloning into 'Projet-tutore-DATA-QUALITY'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (13/13), 4.21 MiB | 2.54 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [65]:
df = spark.read.csv("/content/Projet-tutore-DATA-QUALITY/liste-des-gares.csv", header=True, inferSchema=True, sep=";")
df.show()

+--------+--------------------+----+---------+----------+----------+-------+--------------------+--------------------+--------+--------------------+------------------+------------------+------------------+------------------+--------------------+--------------------+--------------------+
|CODE_UIC|             LIBELLE|FRET|VOYAGEURS|CODE_LIGNE|RG_TRONCON|     PK|             COMMUNE|          DEPARTEMEN|IDRESEAU|              IDGAIA|             X_L93|             Y_L93|           X_WGS84|           Y_WGS84|               C_GEO|           Geo Point|           Geo Shape|
+--------+--------------------+----+---------+----------+----------+-------+--------------------+--------------------+--------+--------------------+------------------+------------------+------------------+------------------+--------------------+--------------------+--------------------+
|87741074|               Culoz|   O|        O|    900000|         1|101+344|               CULOZ|                 AIN|  109976|d9984df0-6667-11e...| 915619.3024000004| 6530817.046300001| 5.778673201716213| 45.84285505626689|45.84285505626689...|45.84285505624967...|"{""coordinates""...|
|87387126|St-Aubin-du-Vieil...|   O|        N|    366000|         1|101+400|     LE VIEIL-EVREUX|                EURE|  109984|c0eb9b80-f312-11e...|  569080.329400003| 6879114.925900001| 1.210685385823276| 48.99860462739372|48.99860462739372...|48.99860462737236...|"{""coordinates""...|
|87694638|             Galuzot|   N|        O|    769000|         1|090+886|       SAINT-VALLIER|      SAONE-ET-LOIRE|  109988|dffa40b4-19bf-11e...| 801732.8373000026| 6616634.444200002| 4.330078799105821| 46.64206758507911|46.64206758507911...|46.64206758506424...|"{""coordinates""...|
|87447649|            Folligny|   O|        O|    415000|         1|075+305|            FOLLIGNY|              MANCHE|  109989|d9b4430e-6667-11e...| 376463.3276000023| 6868037.973000001|-1.409566330036899|48.831073140201674|48.83107314020167...|48.8310731401795,...|"{""coordinates""...|
|87597856|               Croze|   N|        N|    712000|         1|431+082|               CROZE|              CREUSE|  109990|e5443b8c-6667-11e...| 634931.2197000012| 6524607.780099999| 2.161997232072458|45.817998302216694|45.81799830221669...|45.81799830219942...|"{""coordinates""...|
|87721860| Lamure-sur-Azergues|   N|        O|    775000|         1|065+100| LAMURE-SUR-AZERGUES|               RHONE|  109997|d9a5da92-6667-11e...| 815359.5337999985| 6552343.883699998| 4.492313405078927|46.061052468257316|46.06105246825731...|46.06105246824074...|"{""coordinates""...|
|87491720|     Clérac-Charente|   O|        N|    580000|         1|053+943|              CLERAC|   CHARENTE-MARITIME|  110010|293d4c5a-dfbc-11e...|446748.35670000315|6459841.4673999995|-0.225789042171448| 45.19132375598026|45.19132375598026...|45.19132375596121...|"{""coordinates""...|
|87313163| St-Léger-lès-Domart|   N|        N|    322000|         1|032+382|SAINT-LEGER-LES-D...|               SOMME|  110013|d96d6cfc-6667-11e...| 638587.5649000034| 6994767.743999999| 2.143398596424761| 50.04831870759689|50.04831870759689...|50.0483187075806,...|"{""coordinates""...|
|87192278|            Landroff|   N|        N|    140000|         1|113+031|            LANDROFF|             MOSELLE|  110018|e54df9c8-6667-11e...| 964516.4460999966| 6878756.409600001|  6.61308876831267|  48.9542917608136|48.9542917608136,...|48.95429176079202...|"{""coordinates""...|
|87718015|  Besançon-Mouillère|   N|        O|    872000|         1|408+824|            BESANCON|               DOUBS|  110021|e170305a-19bf-11e...| 929463.2210000008| 6686655.203600001| 6.034041759023006| 47.24051893307606|47.24051893307606...|47.24051893306294...|"{""coordinates""...|
|87543066|    Château-Gaillard|   N|        O|    570000|         1|094+447|            SANTILLY|        EURE-ET-LOIR|  110028|e1c86826-19bf-11e...| 619104.8224000037| 6782815.068300001| 1.912395763721251| 48.14068796617873|48.14068796617873...|48.14068796616825...|"{""coordinates""...|
|87491167|   Tugeras-Chartuzac|   N|        N|    500000|         2|547+518|TUGERAS-SAINT-MAU...|   CHARENTE-MARITIME|  110029|e545695e-6667-11e...|  433249.239699997|      6478364.9276| -0.40770246289177| 45.35286395350945|45.35286395350945...|45.35286395349086...|"{""coordinates""...|
|87672741|   Lurbe-St-Christau|   N|        O|    664000|         1|259+597|LURBE-SAINT-CHRISTAU|PYRENEES-ATLANTIQUES|  110034|d9eab782-6667-11e...|406444.42230000347|6231253.0945000015| -0.60561423206694| 43.12021264473371|43.12021264473371...|43.12021264470934...|"{""coordinates""...|
|87575704|  Mignaloux-Nouaillé|   N|        O|    604000|         1|347+859|  MIGNALOUX-BEAUVOIR|              VIENNE|  110038|2955e10c-dfbc-11e...|  501642.370099999| 6606144.133299999| 0.411805714638493| 46.52605001060868|46.52605001060868...|46.52605001059345...|"{""coordinates""...|
|87723700|   Sathonay-Rillieux|   O|        O|    887000|         1|007+000|       SATHONAY-CAMP|               RHONE|  110045|d9e1f27a-6667-11e...| 845832.0820000023|6526508.7886000015| 4.878429559171022| 45.82260534853966|45.82260534853966...|45.8226053485224,...|"{""coordinates""...|
|87682187|Savigny-le-Temple...|   N|        O|    830000|         1|034+289|   SAVIGNY-LE-TEMPLE|      SEINE-ET-MARNE|  110048|d989b250-6667-11e...| 669287.5896999985| 6833069.165199999| 2.583497235662112|48.597097430029166|48.59709743002916...|48.59709743000578...|"{""coordinates""...|
|87491480|St-Même-les-Carri...|   N|        N|    579000|         1|035+072|SAINT-MEME-LES-CA...|            CHARENTE|  110049|e54cc50a-6667-11e...|456055.57599999756| 6511086.142200001|-0.133251146964282| 45.65575861455163|45.65575861455163...|45.65575861453389...|"{""coordinates""...|
|87172049|     Bogny-sur-Meuse|   N|        O|    205000|         1|158+049|     BOGNY-SUR-MEUSE|            ARDENNES|  110051|d9b7b0ee-6667-11e...| 826834.9755000025|      6974757.9298| 4.762681943547026| 49.85885393404695|49.85885393404695...|49.85885393402978...|"{""coordinates""...|
|87755777|             Tourves|   N|        N|    947000|         1|036+038|             TOURVES|                 VAR|  110052|d9ea5542-6667-11e...| 936373.3905000016| 6261392.980799999| 5.917655921477642| 43.41234590175397|43.41234590175397...|43.41234590173027...|"{""coordinates""...|
|87543116|St-Cyr-en-Val-La ...|   O|        O|    590000|         2|133+133|    SAINT-CYR-EN-VAL|              LOIRET|  110078|e03092c6-19bf-11e...| 621247.4794000015| 6747102.818399999| 1.947598303867003|  47.8195968033602|47.8195968033602,...|47.81959680334878...|"{""coordinates""...|
+--------+--------------------+----+---------+----------+----------+-------+--------------------+--------------------+--------+--------------------+------------------+------------------+------------------+------------------+--------------------+--------------------+--------------------+
only showing top 20 rows

In [21]:
df.printSchema()

root
 |-- CODE_UIC: integer (nullable = true)
 |-- LIBELLE: string (nullable = true)
 |-- FRET: string (nullable = true)
 |-- VOYAGEURS: string (nullable = true)
 |-- CODE_LIGNE: integer (nullable = true)
 |-- RG_TRONCON: integer (nullable = true)
 |-- PK: string (nullable = true)
 |-- COMMUNE: string (nullable = true)
 |-- DEPARTEMEN: string (nullable = true)
 |-- IDRESEAU: integer (nullable = true)
 |-- IDGAIA: string (nullable = true)
 |-- X_L93: double (nullable = true)
 |-- Y_L93: double (nullable = true)
 |-- X_WGS84: double (nullable = true)
 |-- Y_WGS84: double (nullable = true)
 |-- C_GEO: string (nullable = true)
 |-- Geo Point: string (nullable = true)
 |-- Geo Shape: string (nullable = true)

In [53]:
from pydeequ.analyzers import *

analysisResult = AnalysisRunner(spark) \
    .onData(df) \
    .addAnalyzer(Size()) \
    .addAnalyzer(Completeness("CODE_UIC")) \
    .addAnalyzer(Distinctness("CODE_UIC")) \
    .addAnalyzer(Completeness("LIBELLE")) \
    .run()



analysisResult_df = AnalyzerContext.successMetricsAsDataFrame(spark, analysisResult)
analysisResult_df.show()

+-------+--------+------------+------------------+
| entity|instance|        name|             value|
+-------+--------+------------+------------------+
|Dataset|       *|        Size|            6469.0|
| Column|CODE_UIC|Completeness|               1.0|
| Column| LIBELLE|Completeness|               1.0|
| Column|CODE_UIC|Distinctness|0.9370845571185654|
+-------+--------+------------+------------------+

In [36]:
# From this, we learn the following:

# review_id has no missing values and approximately 99.27% of the values are distinct
# 74.99% of reviews have a star_rating of 4 or higher
# total_votes and star_rating are not correlated
# helpful_votes and total_votes are strongly correlated
# The average star_rating is 3.99
# The dataset contains 3,010,972 reviews

# .addAnalyzer(Mean("star_rating")) \
# .addAnalyzer(Compliance("top star_rating", "star_rating >= 4.0")) \
# .addAnalyzer(Correlation("total_votes", "star_rating")) \
# .addAnalyzer(Correlation("total_votes", "helpful_votes")) \

# Sometimes, you may want to run multiple metrics on a single column. For example,
# you want to check that all reviews were written either after 1996 or before 2017.
# In this case, it’s helpful to provide a name for each metric in order to
# distinguish the results in the output:

# .addAnalyzer(Compliance("after-1996 review_year", "review_year >= 1996")) \
# .addAnalyzer(Compliance("before-2017 review_year", "review_year <= 2017")) \

# 0.9999993 → 99.99993% of rows have review_year >= 1996
# 0.999999 → 99.999% of rows have review_year <= 2017
# Basically, almost all rows pass your checks.
# If you had a few bad data entries (like 1696 or 2025), they would show up as a small fraction of failures.
# The number is between 0 and 1, representing the proportion of rows that satisfy the condition.
# How to interpret in words
# For your report/presentation, you can write:
# “We verified that almost all review_year values are between 1996 and 2017,
# with compliance scores of ~0.999999. This indicates that the data is largely
# consistent with the expected date range, with only a very small fraction of
# anomalies.”

In [41]:
# For writing tests on data, we start with the VerificationSuite and add checks
# on attributes of the data. In this example, we test for the following
# properties of our data:

# At least 3 million rows in total
# review_id is never null
# review_id is unique
# star_rating has a minimum of 1.0 and maximum of 5.0
# marketplace only contains US, UK, DE, JP, or FR
# year does not contain negative values
# year is between 1996 and 2017
# The following code reflects the previous statements. For information about
# all available checks, see the GitHub repo. You can run this directly in the
# Spark shell as previously explained:

# from pydeequ.checks import *
# from pydeequ.verification import *

# check = Check(spark, CheckLevel.Warning, "Synthetic Product Reviews")

# checkResult = VerificationSuite(spark) \
#     .onData(df) \
#     .addCheck(
#         check.hasSize(lambda x: x >= 3000000) \
#         .hasMin("star_rating", lambda x: x == 1.0) \
#         .hasMax("star_rating", lambda x: x == 5.0)  \
#         .isComplete("review_id")  \
#         .isUnique("review_id")  \
#         .isComplete("marketplace")  \
#         .isContainedIn("marketplace", ["US", "UK", "DE", "JP", "FR"]) \
#         .isNonNegative("year") \
#         .hasMin("review_year", lambda x: x == '1996') \
#         .hasMax("review_year", lambda x: x == '2017')) \
#     .run()

# checkResult_df = VerificationResult.checkResultsAsDataFrame(spark,
# checkResult, pandas=True)

In [49]:
from pydeequ.checks import *
from pydeequ.verification import *


check = Check(spark, CheckLevel.Warning, "Synthetic Product Reviews")

checkResult = VerificationSuite(spark) \
    .onData(df) \
    .addCheck(
        check.hasSize(lambda x: x >= 6000) \
        .isComplete("CODE_UIC") \
        .isUnique("CODE_UIC")
        ) \
    .run()

checkResult_df = VerificationResult.checkResultsAsDataFrame(spark,
checkResult, pandas=True)

In [50]:
checkResult_df.style.set_properties(
    **{
        'overflow-wrap': 'break-word',
        'inline-size': '10px',
    }
)

In [ ]:
# We can also look at all the metrics that Deequ computed for this
# check by running the following:

In [54]:
checkResults_df = VerificationResult.successMetricsAsDataFrame(spark, checkResult, pandas = True)
checkResults_df

    entity  instance          name     value
0  Dataset         *          Size     6,469
1   Column  CODE_UIC  Completeness         1
2   Column  CODE_UIC    Uniqueness 0.8846808

In [ ]:
# Automated Constraint Suggestion
# If you own a large number of datasets or if your dataset has many columns,
# it may be challenging for you to manually define appropriate constraints.
# Deequ can automatically suggest useful constraints based on the data
# distribution. Deequ first runs a data profiling method and then applies a
# set of rules on the result. For more information about how to run a data
# profiling method, see the GitHub repo.

In [55]:
from pydeequ.suggestions import *

suggestionResult = ConstraintSuggestionRunner(spark) \
             .onData(df) \
             .addConstraintRule(DEFAULT()) \
             .run()

# Constraint Suggestions in JSON format
print(json.dumps(suggestionResult, indent=2))

{
  "constraint_suggestions": [
    {
      "constraint_name": "CompletenessConstraint(Completeness(IDGAIA,None,None))",
      "column_name": "IDGAIA",
      "current_value": "Completeness: 1.0",
      "description": "'IDGAIA' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"IDGAIA\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(C_GEO,None,None))",
      "column_name": "C_GEO",
      "current_value": "Completeness: 1.0",
      "description": "'C_GEO' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"C_GEO\")"
    },
    {
      "constraint_name": "UniquenessConstraint(Uniqueness(List(C_GEO),None,None))",
      "column_name": "C_GEO",
      "current_value": "ApproxDistinctness: 1.0259700108208378",
      "description": "'C_GEO' is unique",
      "suggesting_rule": "UniqueIfApproximatelyUniqueRule()",
      "rule_description": "If the ratio of approximate num distinct values in a column is close to the number of records (within the error of the HLL sketch), we suggest a UNIQUE constraint",
      "code_for_constraint": ".isUnique(\"C_GEO\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(PK,None,None))",
      "column_name": "PK",
      "current_value": "Completeness: 1.0",
      "description": "'PK' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"PK\")"
    },
    {
      "constraint_name": "UniquenessConstraint(Uniqueness(List(PK),None,None))",
      "column_name": "PK",
      "current_value": "ApproxDistinctness: 0.940021641675684",
      "description": "'PK' is unique",
      "suggesting_rule": "UniqueIfApproximatelyUniqueRule()",
      "rule_description": "If the ratio of approximate num distinct values in a column is close to the number of records (within the error of the HLL sketch), we suggest a UNIQUE constraint",
      "code_for_constraint": ".isUnique(\"PK\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('VOYAGEURS' has value range 'O', 'N',`VOYAGEURS` IN ('O', 'N'),None,List(VOYAGEURS),None))",
      "column_name": "VOYAGEURS",
      "current_value": "Compliance: 1",
      "description": "'VOYAGEURS' has value range 'O', 'N'",
      "suggesting_rule": "CategoricalRangeRule(com.amazon.deequ.suggestions.rules.CategoricalRangeRule$$$Lambda$3359/0x0000000841345040@228cb320)",
      "rule_description": "If we see a categorical range for a column, we suggest an IS IN (...) constraint",
      "code_for_constraint": ".isContainedIn(\"VOYAGEURS\", [\"O\", \"N\"])"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(VOYAGEURS,None,None))",
      "column_name": "VOYAGEURS",
      "current_value": "Completeness: 1.0",
      "description": "'VOYAGEURS' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"VOYAGEURS\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(CODE_LIGNE,None,None))",
      "column_name": "CODE_LIGNE",
      "current_value": "Completeness: 1.0",
      "description": "'CODE_LIGNE' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"CODE_LIGNE\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('CODE_LIGNE' has no negative values,CODE_LIGNE >= 0,None,List(CODE_LIGNE),None))",
      "column_name": "CODE_LIGNE",
      "current_value": "Minimum: 1000.0",
      "description": "'CODE_LIGNE' has no negative values",
      "suggesting_rule": "NonNegativeNumbersRule()",
      "rule_description": "If we see only non-negative numbers in a column, we suggest a corresponding constraint",
      "code_for_constraint": ".isNonNegative(\"CODE_LIGNE\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('DEPARTEMEN' has value range 'NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR', 'LOT-ET-GARONNE', 'VAUCLUSE', 'AUDE', 'CHARENTE', 'DROME', 'CREUSE', 'CHER', 'FINISTERE', 'MORBIHAN', 'ARDECHE', 'LOZERE', 'HAUTES-ALPES', 'TARN', 'MAYENNE', 'TARN-ET-GARONNE', 'GERS', 'ARIEGE', 'ALPES-DE-HAUTE-PROVENCE', 'TERRITOIRE-DE-BELFORT', 'CORSE-DU-SUD',`DEPARTEMEN` IN ('NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR', 'LOT-ET-GARONNE', 'VAUCLUSE', 'AUDE', 'CHARENTE', 'DROME', 'CREUSE', 'CHER', 'FINISTERE', 'MORBIHAN', 'ARDECHE', 'LOZERE', 'HAUTES-ALPES', 'TARN', 'MAYENNE', 'TARN-ET-GARONNE', 'GERS', 'ARIEGE', 'ALPES-DE-HAUTE-PROVENCE', 'TERRITOIRE-DE-BELFORT', 'CORSE-DU-SUD'),None,List(DEPARTEMEN),None))",
      "column_name": "DEPARTEMEN",
      "current_value": "Compliance: 1",
      "description": "'DEPARTEMEN' has value range 'NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR', 'LOT-ET-GARONNE', 'VAUCLUSE', 'AUDE', 'CHARENTE', 'DROME', 'CREUSE', 'CHER', 'FINISTERE', 'MORBIHAN', 'ARDECHE', 'LOZERE', 'HAUTES-ALPES', 'TARN', 'MAYENNE', 'TARN-ET-GARONNE', 'GERS', 'ARIEGE', 'ALPES-DE-HAUTE-PROVENCE', 'TERRITOIRE-DE-BELFORT', 'CORSE-DU-SUD'",
      "suggesting_rule": "CategoricalRangeRule(com.amazon.deequ.suggestions.rules.CategoricalRangeRule$$$Lambda$3359/0x0000000841345040@228cb320)",
      "rule_description": "If we see a categorical range for a column, we suggest an IS IN (...) constraint",
      "code_for_constraint": ".isContainedIn(\"DEPARTEMEN\", [\"NORD\", \"MOSELLE\", \"PAS-DE-CALAIS\", \"BAS-RHIN\", \"SEINE-MARITIME\", \"OISE\", \"RHONE\", \"AISNE\", \"YVELINES\", \"MEURTHE-ET-MOSELLE\", \"HAUT-RHIN\", \"AIN\", \"SOMME\", \"BOUCHES-DU-RHONE\", \"GIRONDE\", \"LOIRE-ATLANTIQUE\", \"SEINE-ET-MARNE\", \"MARNE\", \"COTE-D'OR\", \"SAONE-ET-LOIRE\", \"PUY-DE-DOME\", \"HAUTE-MARNE\", \"GARD\", \"YONNE\", \"LOIRET\", \"VOSGES\", \"ESSONNE\", \"EURE\", \"INDRE-ET-LOIRE\", \"VAL-D'OISE\", \"HAUTE-SAVOIE\", \"ISERE\", \"HAUTE-GARONNE\", \"CHARENTE-MARITIME\", \"ARDENNES\", \"DORDOGNE\", \"AUBE\", \"HERAULT\", \"SARTHE\", \"EURE-ET-LOIR\", \"NIEVRE\", \"DOUBS\", \"PARIS\", \"VIENNE\", \"JURA\", \"MAINE-ET-LOIRE\", \"LOIRE\", \"SAVOIE\", \"PYRENEES-ATLANTIQUES\", \"LOIR-ET-CHER\", \"PYRENEES-ORIENTALES\", \"HAUTS-DE-SEINE\", \"HAUTE-VIENNE\", \"VENDEE\", \"DEUX-SEVRES\", \"ILLE-ET-VILAINE\", \"MEUSE\", \"HAUTE-LOIRE\", \"CORREZE\", \"CANTAL\", \"ALLIER\", \"CALVADOS\", \"INDRE\", \"ORNE\", \"HAUTE-SAONE\", \"COTES-D'ARMOR\", \"MANCHE\", \"ALPES-MARITIMES\", \"HAUTES-PYRENEES\", \"SEINE-SAINT-DENIS\", \"LOT\", \"AVEYRON\", \"HAUTE-CORSE\", \"LANDES\", \"VAL-DE-MARNE\", \"VAR\", \"LOT-ET-GARONNE\", \"VAUCLUSE\", \"AUDE\", \"CHARENTE\", \"DROME\", \"CREUSE\", \"CHER\", \"FINISTERE\", \"MORBIHAN\", \"ARDECHE\", \"LOZERE\", \"HAUTES-ALPES\", \"TARN\", \"MAYENNE\", \"TARN-ET-GARONNE\", \"GERS\", \"ARIEGE\", \"ALPES-DE-HAUTE-PROVENCE\", \"TERRITOIRE-DE-BELFORT\", \"CORSE-DU-SUD\"])"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(DEPARTEMEN,None,None))",
      "column_name": "DEPARTEMEN",
      "current_value": "Completeness: 1.0",
      "description": "'DEPARTEMEN' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"DEPARTEMEN\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('DEPARTEMEN' has value range 'NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR' for at least 89.0% of values,`DEPARTEMEN` IN ('NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR'),None,List(DEPARTEMEN),None))",
      "column_name": "DEPARTEMEN",
      "current_value": "Compliance: 0.9063224609676915",
      "description": "'DEPARTEMEN' has value range 'NORD', 'MOSELLE', 'PAS-DE-CALAIS', 'BAS-RHIN', 'SEINE-MARITIME', 'OISE', 'RHONE', 'AISNE', 'YVELINES', 'MEURTHE-ET-MOSELLE', 'HAUT-RHIN', 'AIN', 'SOMME', 'BOUCHES-DU-RHONE', 'GIRONDE', 'LOIRE-ATLANTIQUE', 'SEINE-ET-MARNE', 'MARNE', 'COTE-D''OR', 'SAONE-ET-LOIRE', 'PUY-DE-DOME', 'HAUTE-MARNE', 'GARD', 'YONNE', 'LOIRET', 'VOSGES', 'ESSONNE', 'EURE', 'INDRE-ET-LOIRE', 'VAL-D''OISE', 'HAUTE-SAVOIE', 'ISERE', 'HAUTE-GARONNE', 'CHARENTE-MARITIME', 'ARDENNES', 'DORDOGNE', 'AUBE', 'HERAULT', 'SARTHE', 'EURE-ET-LOIR', 'NIEVRE', 'DOUBS', 'PARIS', 'VIENNE', 'JURA', 'MAINE-ET-LOIRE', 'LOIRE', 'SAVOIE', 'PYRENEES-ATLANTIQUES', 'LOIR-ET-CHER', 'PYRENEES-ORIENTALES', 'HAUTS-DE-SEINE', 'HAUTE-VIENNE', 'VENDEE', 'DEUX-SEVRES', 'ILLE-ET-VILAINE', 'MEUSE', 'HAUTE-LOIRE', 'CORREZE', 'CANTAL', 'ALLIER', 'CALVADOS', 'INDRE', 'ORNE', 'HAUTE-SAONE', 'COTES-D''ARMOR', 'MANCHE', 'ALPES-MARITIMES', 'HAUTES-PYRENEES', 'SEINE-SAINT-DENIS', 'LOT', 'AVEYRON', 'HAUTE-CORSE', 'LANDES', 'VAL-DE-MARNE', 'VAR' for at least 89.0% of values",
      "suggesting_rule": "FractionalCategoricalRangeRule(0.9,com.amazon.deequ.suggestions.rules.FractionalCategoricalRangeRule$$$Lambda$3360/0x0000000841345840@66b1b170,WaldIntervalStrategy())",
      "rule_description": "If we see a categorical range for most values in a column, we suggest an IS IN (...) constraint that should hold for most values",
      "code_for_constraint": ".isContainedIn(\"DEPARTEMEN\", [\"NORD\", \"MOSELLE\", \"PAS-DE-CALAIS\", \"BAS-RHIN\", \"SEINE-MARITIME\", \"OISE\", \"RHONE\", \"AISNE\", \"YVELINES\", \"MEURTHE-ET-MOSELLE\", \"HAUT-RHIN\", \"AIN\", \"SOMME\", \"BOUCHES-DU-RHONE\", \"GIRONDE\", \"LOIRE-ATLANTIQUE\", \"SEINE-ET-MARNE\", \"MARNE\", \"COTE-D'OR\", \"SAONE-ET-LOIRE\", \"PUY-DE-DOME\", \"HAUTE-MARNE\", \"GARD\", \"YONNE\", \"LOIRET\", \"VOSGES\", \"ESSONNE\", \"EURE\", \"INDRE-ET-LOIRE\", \"VAL-D'OISE\", \"HAUTE-SAVOIE\", \"ISERE\", \"HAUTE-GARONNE\", \"CHARENTE-MARITIME\", \"ARDENNES\", \"DORDOGNE\", \"AUBE\", \"HERAULT\", \"SARTHE\", \"EURE-ET-LOIR\", \"NIEVRE\", \"DOUBS\", \"PARIS\", \"VIENNE\", \"JURA\", \"MAINE-ET-LOIRE\", \"LOIRE\", \"SAVOIE\", \"PYRENEES-ATLANTIQUES\", \"LOIR-ET-CHER\", \"PYRENEES-ORIENTALES\", \"HAUTS-DE-SEINE\", \"HAUTE-VIENNE\", \"VENDEE\", \"DEUX-SEVRES\", \"ILLE-ET-VILAINE\", \"MEUSE\", \"HAUTE-LOIRE\", \"CORREZE\", \"CANTAL\", \"ALLIER\", \"CALVADOS\", \"INDRE\", \"ORNE\", \"HAUTE-SAONE\", \"COTES-D'ARMOR\", \"MANCHE\", \"ALPES-MARITIMES\", \"HAUTES-PYRENEES\", \"SEINE-SAINT-DENIS\", \"LOT\", \"AVEYRON\", \"HAUTE-CORSE\", \"LANDES\", \"VAL-DE-MARNE\", \"VAR\"], lambda x: x >= 0.89, \"It should be above 0.89!\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(Y_L93,None,None))",
      "column_name": "Y_L93",
      "current_value": "Completeness: 1.0",
      "description": "'Y_L93' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"Y_L93\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('Y_L93' has no negative values,Y_L93 >= 0,None,List(Y_L93),None))",
      "column_name": "Y_L93",
      "current_value": "Minimum: 6109212.647",
      "description": "'Y_L93' has no negative values",
      "suggesting_rule": "NonNegativeNumbersRule()",
      "rule_description": "If we see only non-negative numbers in a column, we suggest a corresponding constraint",
      "code_for_constraint": ".isNonNegative(\"Y_L93\")"
    },
    {
      "constraint_name": "UniquenessConstraint(Uniqueness(List(Y_L93),None,None))",
      "column_name": "Y_L93",
      "current_value": "ApproxDistinctness: 1.026433761014067",
      "description": "'Y_L93' is unique",
      "suggesting_rule": "UniqueIfApproximatelyUniqueRule()",
      "rule_description": "If the ratio of approximate num distinct values in a column is close to the number of records (within the error of the HLL sketch), we suggest a UNIQUE constraint",
      "code_for_constraint": ".isUnique(\"Y_L93\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(X_WGS84,None,None))",
      "column_name": "X_WGS84",
      "current_value": "Completeness: 1.0",
      "description": "'X_WGS84' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"X_WGS84\")"
    },
    {
      "constraint_name": "UniquenessConstraint(Uniqueness(List(X_WGS84),None,None))",
      "column_name": "X_WGS84",
      "current_value": "ApproxDistinctness: 0.9859329108053795",
      "description": "'X_WGS84' is unique",
      "suggesting_rule": "UniqueIfApproximatelyUniqueRule()",
      "rule_description": "If the ratio of approximate num distinct values in a column is close to the number of records (within the error of the HLL sketch), we suggest a UNIQUE constraint",
      "code_for_constraint": ".isUnique(\"X_WGS84\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('FRET' has value range 'N', 'O',`FRET` IN ('N', 'O'),None,List(FRET),None))",
      "column_name": "FRET",
      "current_value": "Compliance: 1",
      "description": "'FRET' has value range 'N', 'O'",
      "suggesting_rule": "CategoricalRangeRule(com.amazon.deequ.suggestions.rules.CategoricalRangeRule$$$Lambda$3359/0x0000000841345040@228cb320)",
      "rule_description": "If we see a categorical range for a column, we suggest an IS IN (...) constraint",
      "code_for_constraint": ".isContainedIn(\"FRET\", [\"N\", \"O\"])"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(FRET,None,None))",
      "column_name": "FRET",
      "current_value": "Completeness: 1.0",
      "description": "'FRET' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"FRET\")"
    },
    {
      "constraint_name": "CompletenessConstraint(Completeness(X_L93,None,None))",
      "column_name": "X_L93",
      "current_value": "Completeness: 1.0",
      "description": "'X_L93' is not null",
      "suggesting_rule": "CompleteIfCompleteRule()",
      "rule_description": "If a column is complete in the sample, we suggest a NOT NULL constraint",
      "code_for_constraint": ".isComplete(\"X_L93\")"
    },
    {
      "constraint_name": "ComplianceConstraint(Compliance('X_L93' has no negative values,X_L93 >= 0,None,List(X_L93),None))",
      "column_name": "X_L93",
      "current_value": "Minimum: 147234.81379999965",
      "description": "'X_L93' has no negative values",
      "suggesting_rule": "NonNegativeNumbersRule()",
      "rule_description": "If we see only non-negative numbers in a column, we suggest a corresponding constraint",
      "code_for_constraint": ".isNonNegative(\"X_L93\")"
    },
    {